Mini Challenge 1
erickwize/react-certification-2020 pull request #12
Opened 2021-03-19 21:13 UTC by solics

I changed .gitignore and added .prettierrc & .eslintrc files because I think some developers has in mind different rules for best coding

2021-03-22 02:22 UTC, MartinMolinero requested changes
Hello Solimar, thanks for submitting your project, you are making great progress on it! I would suggest you to review the content we saw on the workshop about testing. Also try to remove the `Renders without crashing` tests that don't trigger an expect statement, since you are not proving any kind of behavior of your components on them.
Apart from that, the components and the structure of your project, look good 😄

2021-03-22 02:22 UTC, MartinMolinero commented on src/__test__/components/Header.test.js
> +	it('Click toggle', () => {
This test is missing the goal you're trying to prove in it.

2021-03-22 02:22 UTC, MartinMolinero commented on src/__test__/components/VideoCard.test.js
> +describe('VideoCard testing', () => {
Maybe in this test file you can check different things on your video card.
Try grabing one item and verifying all the content of the videocard, for example:
- That when rendering the title it matches with the real information you are sending by props.
- That the src of the thumbnail matches with the correct item.
etc, etc.

2021-03-22 02:22 UTC, MartinMolinero commented on src/__test__/components/VideoCard.test.js
> +	it('Renders without crashing', () => {
You can delete this kind of tests.

2021-03-22 02:22 UTC, MartinMolinero commented on src/__test__/components/VideosList.test.js
> +	it('Renders without crashing', () => {
You can delete this kind of tests.

2021-03-22 02:22 UTC, MartinMolinero commented on src/__test__/pages/Home.test.js
> +	it('Renders without crashing', () => {
You can delete this kind of tests.

2021-03-22 02:22 UTC, MartinMolinero commented on src/__test__/components/Header.test.js
> +	it('Renders without crashing', () => {
You can delete this test, since you are just triggering a render, but not proving any behavior or content in the component.

2021-03-22 02:22 UTC, MartinMolinero commented on src/__test__/components/Layout.test.js
> +	it('Renders without crashing', () => {
You can delete this kind of tests.

2021-03-22 02:58 UTC, MartinMolinero commented
If you need help with test after reviewing the content and the content of last Wednesday's workshop please let me know!

2021-03-22 15:05 UTC, solics commented
Hi Martin

Thank you for your feedback, and yes I'd like to schedule a meeting,
because I felt a little blocked while doing testing. Would you have time
tomorrow, at 6:30pm(peruvian time) or maybe today. I have some doubts about
testing and styled components.

Thank you for your time.

El dom., 21 de marzo de 2021 9:58 p. m., Martín Molinero <
***@***.***> escribió:

> If you need help with test after reviewing the content and the content of
> last Wednesday's workshop please let me know!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/erickwize/react-certification-2020/pull/12#issuecomment-803727718>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOANCKXVCK2F357B3K4JI3TE2W47ANCNFSM4ZPQRJYQ>
> .
>

2021-04-05 21:28 UTC, MartinMolinero reviewed
In terms of implementation, everything seems good. Just a couple of suggestions on how to manage the related videos and to get into cleaner code practices. Nice progress! Now focus on testing and the next steps.

2021-04-05 21:28 UTC, MartinMolinero commented on src/context/YoutubeContext.js
> +		},
I would suggest you to rewrite all the searching and setting videos into a separate function in order to have cleaner code.

2021-04-05 21:28 UTC, MartinMolinero commented on src/customHooks/useVideoDetail.js
> +	const relatedVideos = useMemo(() => {
Just as a side note, I think there's an specific endpoint to gather the related videos of a specific videos, maybe that could help you out in order to visualize real results and you can trigger the fetching of the related videos everytime the url changes

2021-04-15 02:57 UTC, solics commented
![image](https://user-images.githubusercontent.com/1836681/114807451-0e7c7b80-9d6c-11eb-9f97-4798bc3de9a8.png)
Hi Martin, thank you for your previous feedback, I know there's a lot to improve and I need you to let me know it please, btw here is a screenshot of my coverage report

2021-07-02 20:45 UTC, closed without merging